//tasks.js
export const tasksDummy = [
  {
    id: '1',
    title: 'Buy groceries',
    description: 'Milk, eggs, bread, fruits',
    status: 'Pending',
    dueDate: '2025-07-05',
  },
  {
    id: '2',
    title: 'Finish report',
    description: 'Complete the quarterly sales report',
    status: 'In Progress',
    dueDate: '2025-07-10',
  },
  {
    id: '3',
    title: 'Call mom',
    description: 'Wish her happy birthday',
    status: 'Completed',
    dueDate: '2025-06-30',
  },
  {
    id: '4',
    title: 'Team Call',
    description: 'Project Discussion',
    status: 'Overdue',
    dueDate: '2025-06-21',
  },
  {
    id: '5',
    title: 'Exercise',
    description: '30 minutes cardio',
    status: 'Pending',
    dueDate: '2025-07-03',
  },
  {
    id: '6',
    title: 'Review PR',
    description: 'Check new pull request on GitHub',
    status: 'In Progress',
    dueDate: '2025-07-06',
  },
  {
    id: '7',
    title: 'Client Meeting',
    description: 'Discuss project timeline',
    status: 'Pending',
    dueDate: '2025-07-04',
  },
  {
    id: '8',
    title: 'Book Tickets',
    description: 'Flight tickets to Delhi',
    status: 'Completed',
    dueDate: '2025-06-25',
  },
  {
    id: '9',
    title: 'Backup Data',
    description: 'Backup all important files',
    status: 'Overdue',
    dueDate: '2025-06-20',
  },
  {
    id: '10',
    title: 'Water Plants',
    description: 'Indoor and balcony plants',
    status: 'Pending',
    dueDate: '2025-07-03',
  },
  {
    id: '11',
    title: 'Renew License',
    description: 'Driving license renewal',
    status: 'In Progress',
    dueDate: '2025-07-11',
  },
  {
    id: '12',
    title: 'Team Lunch',
    description: 'Schedule lunch with team',
    status: 'Pending',
    dueDate: '2025-07-07',
  },
  {
    id: '13',
    title: 'Pay Bills',
    description: 'Electricity and internet',
    status: 'Completed',
    dueDate: '2025-07-01',
  },
  {
    id: '14',
    title: 'Read Book',
    description: 'Finish reading "Atomic Habits"',
    status: 'Pending',
    dueDate: '2025-07-15',
  },
  {
    id: '15',
    title: 'Fix Bug #402',
    description: 'Resolve login redirect issue',
    status: 'In Progress',
    dueDate: '2025-07-09',
  },
  {
    id: '16',
    title: 'Grocery Delivery',
    description: 'Schedule online grocery delivery',
    status: 'Completed',
    dueDate: '2025-06-28',
  },
  {
    id: '17',
    title: 'Update Resume',
    description: 'Add recent project experience',
    status: 'Pending',
    dueDate: '2025-07-12',
  },
  {
    id: '18',
    title: 'Dentist Appointment',
    description: 'Routine dental checkup',
    status: 'Overdue',
    dueDate: '2025-06-26',
  },
  {
    id: '19',
    title: 'Yoga Session',
    description: '1-hour morning session',
    status: 'Pending',
    dueDate: '2025-07-04',
  },
  {
    id: '20',
    title: 'Submit Invoice',
    description: 'Send June invoice to client',
    status: 'Completed',
    dueDate: '2025-07-02',
  },
  {
    id: '21',
    title: 'Organize Desk',
    description: 'Declutter workspace',
    status: 'Pending',
    dueDate: '2025-07-08',
  },
  {
    id: '22',
    title: 'Fix Footer',
    description: 'Fix alignment issue in footer',
    status: 'In Progress',
    dueDate: '2025-07-10',
  },
  {
    id: '23',
    title: 'Refactor Code',
    description: 'Clean up legacy code',
    status: 'Pending',
    dueDate: '2025-07-14',
  },
  {
    id: '24',
    title: 'Car Service',
    description: 'Schedule annual maintenance',
    status: 'Overdue',
    dueDate: '2025-06-29',
  },
  {
    id: '25',
    title: 'Client Feedback',
    description: 'Collect feedback from last demo',
    status: 'Completed',
    dueDate: '2025-06-30',
  },
  {
    id: '26',
    title: 'Watch Webinar',
    description: 'Attend React performance webinar',
    status: 'Pending',
    dueDate: '2025-07-09',
  },
  {
    id: '27',
    title: 'Prepare Slides',
    description: 'Design slides for presentation',
    status: 'In Progress',
    dueDate: '2025-07-08',
  },
  {
    id: '28',
    title: 'Write Blog',
    description: 'Publish weekly tech blog',
    status: 'Pending',
    dueDate: '2025-07-06',
  },
  {
    id: '29',
    title: 'Family Dinner',
    description: 'Dinner with cousins',
    status: 'Completed',
    dueDate: '2025-06-22',
  },
  {
    id: '30',
    title: 'Watch Movie',
    description: 'Go to cinema for new release',
    status: 'Pending',
    dueDate: '2025-07-13',
  },
  {
    id: '31',
    title: 'Update Portfolio',
    description: 'Add new case studies',
    status: 'In Progress',
    dueDate: '2025-07-15',
  },
  {
    id: '32',
    title: 'Design Logo',
    description: 'Logo for new product',
    status: 'Pending',
    dueDate: '2025-07-12',
  },
  {
    id: '33',
    title: 'Set Up Email',
    description: 'Configure domain email',
    status: 'Completed',
    dueDate: '2025-06-27',
  },
  {
    id: '34',
    title: 'Brainstorm Ideas',
    description: 'New feature brainstorming session',
    status: 'Pending',
    dueDate: '2025-07-10',
  },
  {
    id: '35',
    title: 'Review Docs',
    description: 'Review API documentation',
    status: 'In Progress',
    dueDate: '2025-07-09',
  },
  {
    id: '36',
    title: 'Onboard Intern',
    description: 'First-day orientation',
    status: 'Completed',
    dueDate: '2025-06-30',
  },
  {
    id: '37',
    title: 'Clean House',
    description: 'Weekend cleanup',
    status: 'Pending',
    dueDate: '2025-07-05',
  },
  {
    id: '38',
    title: 'Write Tests',
    description: 'Unit testing with Jest',
    status: 'In Progress',
    dueDate: '2025-07-11',
  },
  {
    id: '39',
    title: 'Fix Navbar',
    description: 'Responsive navbar bug',
    status: 'Pending',
    dueDate: '2025-07-04',
  },
  {
    id: '40',
    title: 'Push to Git',
    description: 'Push final changes',
    status: 'Completed',
    dueDate: '2025-07-02',
  },
  {
    id: '41',
    title: 'Conduct Interviews',
    description: 'Frontend dev candidates',
    status: 'Overdue',
    dueDate: '2025-06-25',
  },
  {
    id: '42',
    title: 'Office Setup',
    description: 'Setup second monitor',
    status: 'Pending',
    dueDate: '2025-07-07',
  },
  {
    id: '43',
    title: 'Team Feedback',
    description: 'Collect feedback from sprint',
    status: 'Completed',
    dueDate: '2025-07-01',
  },
  {
    id: '44',
    title: 'Learn Tailwind',
    description: 'Start TailwindCSS course',
    status: 'Pending',
    dueDate: '2025-07-15',
  },
  {
    id: '45',
    title: 'Test Deployment',
    description: 'Check staging server',
    status: 'In Progress',
    dueDate: '2025-07-13',
  },
  {
    id: '46',
    title: 'Plan Sprint',
    description: 'Define goals and backlog',
    status: 'Pending',
    dueDate: '2025-07-10',
  },
  {
    id: '47',
    title: 'Daily Standup',
    description: 'Share team updates',
    status: 'Pending',
    dueDate: '2025-07-03',
  },
  {
    id: '48',
    title: 'Test Forms',
    description: 'Test all form validations',
    status: 'In Progress',
    dueDate: '2025-07-14',
  },
  {
    id: '49',
    title: 'Plan Vacation',
    description: 'Book resort and travel',
    status: 'Pending',
    dueDate: '2025-07-20',
  },
  {
    id: '50',
    title: 'Update Docs',
    description: 'Update internal docs for API',
    status: 'Completed',
    dueDate: '2025-07-01',
  },
];
